### ISSUE TITLE
Xndroid 在安卓8.1上无法运行，持续崩溃。

### ISSUE THREAD

**Issue by Soapere** [XndroidDev/Xndroid#112]
如题，且无法将xndroid移到内部储存中。

**Comment by Soapere** [comment]
在五月安全补丁之前也没这个问题。

**Comment by iopxiang** [comment]
nexus 6p 六月更新了 没问题，卸载了重装一下试试

**Comment by Soapere** [comment]
没用。。。

**Comment by caofengzi** [comment]
這個是否與原生和非原生系統有關呢？俺也是8.1五月安全補丁沒問題。

**Comment by XndroidDev** [comment]
"无法将xndroid移到内部储存中" 是指什么？ 外置存储卡为默认存储卡？

**Comment by Soapere** [comment]
是的，外置默认。我用的是aosp extended.

**Comment by Soapere** [comment]
比xx-net体积大的应用都能移动。但移动xx-net时提示存储空间不足。

**Comment by Soapere** [comment]
换rom也没用。crdroid也是这样。。。

**Comment by XndroidDev** [comment]
```
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Activity.runOnUiThread(java.lang.Runnable)' on a null object reference
	at net.xndroid.LaunchService.chooseLaunchMode(LaunchService.java:205)
	at net.xndroid.LaunchService.isRunInRootMode(LaunchService.java:235)
	at net.xndroid.LaunchService.shellInit(LaunchService.java:308)
	at net.xndroid.LaunchService.access$500(LaunchService.java:39)
	at net.xndroid.LaunchService$3.work(LaunchService.java:405)
	at net.xndroid.WorkingDlg$1.run(WorkingDlg.java:17)
	at java.lang.Thread.run(Thread.java:764)
```
https://github.com/XndroidDev/Xndroid/blob/b2adeb07b85566689d996d35b2ba6a4ae24ed3f6/app/src/main/java/net/xndroid/LaunchService.java#L205

sActivity为null，原因未知，难道LaunchService与MainActivity不在同一进程中？
