### ISSUE TITLE
致命错误，无法启动，1.2.2版本

### ISSUE THREAD

**Issue by feng3843** [XndroidDev/Xndroid#128]
启动报错
calling startActivity() from outside of an activity context requires flag FLAG_ACTIVITY_ NEW_TASK flag
红米note4x 
安卓6.1

**Comment by XndroidDev** [comment]
请上传日志

**Comment by stonyz** [comment]
碰到同样错误，
```java
[06:54:36    INFO] >>>~ /data/data/net.xndroid/files/xndroid_files/busybox chmod 777 /data/data/net.xndroid/files/xndroid_files/xxnet/data/gae_proxy/CA.crt
[06:54:36    INFO] ShOut> 
[06:54:36    INFO] >>>~ /data/data/net.xndroid/files/xndroid_files/busybox cp -f /data/data/net.xndroid/files/xndroid_files/xxnet/data/gae_proxy/CA.crt /sdcard/XX-Net.crt
[06:54:36    INFO] ShOut> 
[06:54:36   ERROR] launch fail 
android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
	at android.app.ContextImpl.startActivity(ContextImpl.java:1112)
	at android.app.ContextImpl.startActivity(ContextImpl.java:1093)
	at android.content.ContextWrapper.startActivity(ContextWrapper.java:311)
	at net.xndroid.xxnet.XXnetManager.importCert(XXnetManager.java:416)
	at net.xndroid.xxnet.XXnetManager.autoImportCA(XXnetManager.java:290)
	at net.xndroid.xxnet.XXnetManager.waitReady(XXnetManager.java:267)
	at net.xndroid.LaunchService$3.run(LaunchService.java:399)
	at net.xndroid.WorkingDlg$1.run(WorkingDlg.java:23)
	at java.lang.Thread.run(Thread.java:841)
```
完整日志见附件
[xndroid-logs.tar.gz](https://github.com/XndroidDev/Xndroid/files/2251387/xndroid-logs.tar.gz)

**Comment by hjfeng1988** [comment]
同样错误，calling startActivity() from outside of an activity context requires flag FLAG_ACTIVITY_ NEW_TASK flag
华为 麦芒5 安卓6.0
[xndroid-logs.tar.gz](https://github.com/XndroidDev/Xndroid/files/2276308/xndroid-logs.tar.gz)

**Comment by XndroidDev** [comment]
已解决, 下载最新测试版https://raw.githubusercontent.com/XndroidDev/Xndroid-update/master/update/app-debug.apk
