### ISSUE TITLE
能不能fqrouter添加個ss二維碼掃描功能

### ISSUE THREAD

**Issue by fengkuangfanqiang** [XndroidDev/Xndroid#143]
xx-net沒法用老是崩潰。只能禁止了。禁止后程序可以啓動了。但是ss輸入太麻煩貌似也連不上網鬱悶。pc上倒是什麽問題都沒有xx-net,ss都能用。安卓機子真麻煩.上傳也不會。下面看了半天一堆失敗我貼點看看。
================================================================================
2018-07-15 00:24:49,224 INFO tcp://142.4.205.47:443 resolved facebook.com => ['31.13.80.36'], took 1.97
2018-07-15 00:24:49,232 DEBUG [192.168.1.102:38849 => 61.135.169.121:443 DirectProxy] done
2018-07-15 00:24:49,253 DEBUG [192.168.1.102:56703 => 123.129.215.222:443 DirectProxy] done
2018-07-15 00:24:49,323 DEBUG received downstream request from ('192.168.1.102', 52112): DNS(qd=[Q(type=28, name='nim.qiyukf.com')], id=22276)
2018-07-15 00:24:49,430 DEBUG forward response to downstream ('192.168.1.102', 52112): DNS(qd=[Q(type=28, name='nim.qiyukf.com')], id=22276, op=33027)
2018-07-15 00:24:49,436 DEBUG [192.168.1.102:41378 => 223.252.207.30:443] downstream connected
2018-07-15 00:24:49,479 DEBUG [192.168.1.102:41378 => 223.252.207.30:443 DirectProxy] direct upstream connected
2018-07-15 00:24:49,518 DEBUG [192.168.1.102:57186 => 118.89.204.100:443 DirectProxy] done
2018-07-15 00:24:49,727 DEBUG [192.168.1.102:41378 => 223.252.207.30:443 DirectProxy] done
2018-07-15 00:24:50,264 ERROR failed to connect to 113.20.8.17:443
Traceback (most recent call last):
  File "/data/data/net.xndroid/files/xndroid_files/fqrouter/manager/fqdns.py", line 546, in resolve_over_tcp
    sock = create_tcp_socket(server_ip, server_port, connect_timeout=3)
  File "/data/data/net.xndroid/files/xndroid_files/fqrouter/manager/fqdns.py", line 731, in create_tcp_socket
    return SPI['create_tcp_socket'](server_ip, server_port, connect_timeout)
  File "/data/data/net.xndroid/files/xndroid_files/fqrouter/manager/fqdns.py", line 741, in _create_tcp_socket
    sock.connect((server_ip, server_port))
  File "/home/dejavu/Projects/python-for-android/build/python-install/lib/python2.7/site-packages/gevent/socket.py", line 347, in connect
  File "/home/dejavu/Projects/python-for-android/build/python-install/lib/python2.7/site-packages/gevent/socket.py", line 298, in _wait
  File "/home/dejavu/Projects/python-for-android/build/python-install/lib/python2.7/site-packages/gevent/hub.py", line 341, in wait
  File "/home/dejavu/Projects/python-for-android/build/python-install/lib/python2.7/site-packages/gevent/hub.py", line 568, in get
  File "/home/dejavu/Projects/python-for-android/build/python-install/lib/python2.7/site-packages/gevent/hub.py", line 331, in switch
timeout: timed out
2018-07-15 00:24:50,281 ERROR failed to connect to 95.141.34.162:5678
Traceback (most recent call last):
  File "/data/data/net.xndroid/files/xndroid_files/fqrouter/manager/fqdns.py", line 546, in resolve_over_tcp
    sock = create_tcp_socket(server_ip, server_port, connect_timeout=3)
  File "/data/data/net.xndroid/files/xndroid_files/fqrouter/manager/fqdns.py", line 731, in create_tcp_socket
    return SPI['create_tcp_socket'](server_ip, server_port, connect_timeout)
  File "/data/data/net.xndroid/files/xndroid_files/fqrouter/manager/fqdns.py", line 741, in _create_tcp_socket
    sock.connect((server_ip, server_port))
  File "/home/dejavu/Projects/python-for-android/build/python-install/lib/python2.7/site-packages/gevent/socket.py", line 347, in connect
  File "/home/dejavu/Projects/python-for-android/build/python-install/lib/python2.7/site-packages/gevent/socket.py", line 298, in _wait
  File "/home/dejavu/Projects/python-for-android/build/python-install/lib/python2.7/site-packages/gevent/hub.py", line 341, in wait
  File "/home/dejavu/Projects/python-for-android/build/python-install/lib/python2.7/site-packages/gevent/hub.py", line 568, in get
  File "/home/dejavu/Projects/python-for-android/build/python-install/lib/python2.7/site-packages/gevent/hub.py", line 331, in switch
timeout: timed out
[00:24:12    INFO] sockVpnService start
[00:24:13    INFO] init skipped fd count: 5
[00:24:15    INFO] create a persistent udp socket
[00:24:16    INFO] startVpn, teredo_ip is 2001:0:53aa:64c:182b:ed3b:c3fe:f11d
[00:24:16   ERROR] connect 146.185.134.104:54 failed
[00:24:16    INFO] tunFD is 48
[00:24:16    INFO] Started in VPN mode
[00:24:17   ERROR] connect 80.90.43.162:5678 failed
[00:24:17    INFO] send TUN fd
[00:24:19   ERROR] connect 95.141.34.162:5678 failed
[00:24:19   ERROR] connect 142.4.205.47:443 failed
[00:24:19   ERROR] connect 113.20.8.17:443 failed
[00:24:43    INFO] network change, use_mobile_network=false
[00:24:43   DEBUG] get fail:failed to connect to /127.0.0.1 (port 2515) after 1500ms: isConnected failed: ECONNREFUSED (Connection refused) url: http://127.0.0.1:2515/ping
[00:24:43    INFO] try to start fqrouter, cmd: cd /data/data/net.xndroid/files/xndroid_files 
export PATH=/data/data/net.xndroid/files/xndroid_files:$PATH
export DEBUG=TRUE
sh /data/data/net.xndroid/files/xndroid_files/python/bin/python-launcher-nopie.sh /data/data/net.xndroid/files/xndroid_files/fqrouter/manager/main.py run  > /data/data/net.xndroid/files/xndroid_files/log/fqrouter-output.log 2>&1 
exit

[00:24:43   DEBUG] ping failed: 
[00:24:44   DEBUG] get fail:failed to connect to /127.0.0.1 (port 2515) after 1500ms: isConnected failed: ECONNREFUSED (Connection refused) url: http://127.0.0.1:2515/ping
[00:24:44   DEBUG] ping failed: 
[00:24:44    INFO] battery:82%, BatteryLow=false
[00:24:45   DEBUG] get fail:failed to connect to /127.0.0.1 (port 2515) after 1500ms: isConnected failed: ECONNREFUSED (Connection refused) url: http://127.0.0.1:2515/ping
[00:24:45   DEBUG] ping failed: 
[00:24:46   DEBUG] get fail:failed to connect to /127.0.0.1 (port 2515) after 1500ms: isConnected failed: ECONNREFUSED (Connection refused) url: http://127.0.0.1:2515/ping
[00:24:46   DEBUG] ping failed: 
[00:24:47   DEBUG] get fail:failed to connect to /127.0.0.1 (port 2515) after 1500ms: isConnected failed: ECONNREFUSED (Connection refused) url: http://127.0.0.1:2515/ping
[00:24:47   DEBUG] ping failed: 
[00:24:48    INFO] ping succeeded
[00:24:48   DEBUG] get fail:failed to connect to /127.0.0.1 (port 8085) after 1500ms: isConnected failed: ECONNREFUSED (Connection refused) url: http://127.0.0.1:8085/module/gae_proxy/control/status
[00:24:48   DEBUG] get json fail.
[00:24:48   DEBUG] get fail:failed to connect to /127.0.0.1 (port 8085) after 1500ms: isConnected failed: ECONNREFUSED (Connection refused) url: http://127.0.0.1:8085/module/gae_proxy/control/scan_ip?cmd=get_range
[00:24:48    INFO] try to start xxnet, cmd: cd /data/data/net.xndroid/files/xndroid_files 
export LANG=zh_CN 
export PATH=/data/data/net.xndroid/files/xndroid_files:$PATH
export DEBUG=TRUE
sh /data/data/net.xndroid/files/xndroid_files/python/bin/python-launcher-nopie.sh /data/data/net.xndroid/files/xndroid_files/xxnet/android_start.py protect_sock root_mode > /data/data/net.xndroid/files/xndroid_files/log/xxnet-output.log 2>&1 
exit

[00:24:48   DEBUG] get fail:failed to connect to /127.0.0.1 (port 8085) after 1500ms: isConnected failed: ECONNREFUSED (Connection refused) url: http://127.0.0.1:8085/module/gae_proxy/control/status
[00:24:48   DEBUG] get json fail.
[00:24:49   DEBUG] get fail:failed to connect to /127.0.0.1 (port 8085) after 1500ms: isConnected failed: ECONNREFUSED (Connection refused) url: http://127.0.0.1:8085/module/gae_proxy/control/status
[00:24:49   DEBUG] get json fail.
[00:24:50   DEBUG] get fail:failed to connect to /127.0.0.1 (port 8085) after 1500ms: isConnected failed: ECONNREFUSED (Connection refused) url: http://127.0.0.1:8085/module/gae_proxy/control/status
[00:24:50   DEBUG] get json fail.
[00:24:50    INFO] xxnet exit output :

[00:24:50    INFO] xxnet exit error :

[00:24:50   ERROR] FatalError: XX-Net意外退出

**Comment by XndroidDev** [comment]
单纯使用ss的话建议使用ss客户端, 会省电一些.  关于崩溃的问题请上传完整的日志
