### ISSUE TITLE
请问家里的路由器是没有ipv6设置的，是不是不能用这个？

### ISSUE THREAD

**Issue by glhfgg1024** [XndroidDev/Xndroid#149]
家里的那个路由器是中国电信的，进入那个设置页面，看不到可以设置ipv6的，只有ipv4的局域网址。在笔记本上可以用xx-net成功联网访问google。但是安装了xndroid后，一直显示是“等待扫描ip，建议开启ipv6”。手机是android 5.0，看那个wlan网址，既有ipv4地址又有ipv6地址。我不知道哪里出错了，麻烦您看一下，谢谢！

**Comment by AnyWAT** [comment]
貌似不是路由器使用XX-Net，与有没有ipv6设置没有影响。
android 4.4.2正常运行。xndroid 版本？其内XX-Net版本？

**Comment by glhfgg1024** [comment]
@AnyWAT, 谢谢回复！试了几个版本，1.2.2那个版本打开后会出现一个“致命错误，...startActivity...”类似地错误，然后只能退出。但是可以透过那个弹出窗口看到“现在可以访问互联网了”的字样，而且在浏览器里打开google是可以访问的。但是点了退出后，程序就退出了，不能设置里面的app id等。

**Comment by AnyWAT** [comment]
基于 https://github.com/XX-net/XX-Net/issues/11183 公告转贴，貌似其内XX-Net 只能是修复了证书问题的 3.12.2及以后版本

**Comment by glhfgg1024** [comment]
@AnyWAT, 请看一下如下截图。把这个程序最小化后，打开浏览器可以访问google。但是点退出后程序就停止运行了。
![screenshot_2018-07-29-16-15-43-100_net xndroid](https://user-images.githubusercontent.com/30264480/43364344-0deaaa58-934b-11e8-9d8e-d8778d02369a.png)

**Comment by AnyWAT** [comment]
不识代码😭

**Comment by glhfgg1024** [comment]
@SeaHOH 谢谢回复！

我查看了日志，错误如下：
>>>~ /data/data/net.xndroid/files/xndroid_files/busybox cp -f /data/data/net.xndroid/files/xndroid_files/xxnet/data/gae_proxy/CA.crt /sdcard/XX-Net.crt
[16:26:42    INFO] ShOut> 
[16:26:42   ERROR] launch fail 
android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
	at android.app.ContextImpl.startActivity(ContextImpl.java:1363)
	at android.app.ContextImpl.startActivity(ContextImpl.java:1350)
	at android.content.ContextWrapper.startActivity(ContextWrapper.java:332)
	at net.xndroid.xxnet.XXnetManager.importCert(XXnetManager.java:416)
	at net.xndroid.xxnet.XXnetManager.autoImportCA(XXnetManager.java:290)
	at net.xndroid.xxnet.XXnetManager.waitReady(XXnetManager.java:267)
	at net.xndroid.LaunchService$3.run(LaunchService.java:399)
	at net.xndroid.WorkingDlg$1.run(WorkingDlg.java:23)
	at java.lang.Thread.run(Thread.java:818)

[16:26:42   ERROR] FatalError: unexpected exception: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
[16:26:42    INFO] >>>~ /data/data/net.xndroid/files/xndroid_files/busybox tar -czf /sdcard/xndroid-logs.tar.gz -C /data/data/net.xndroid/files/xndroid_files log/ fqrouter/log/

我搜索了一下源代码和解决办法，根据如下描述：
https://stackoverflow.com/questions/3918517/calling-startactivity-from-outside-of-an-activity-context
可能需要在
https://github.com/XndroidDev/Xndroid/blob/3fc9a7119f0065c1f9a52d72d7b91271bf213297/app/src/main/java/net/xndroid/xxnet/XXnetManager.java#L416
这一行前面添加：
installIntent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);

**Comment by AnyWAT** [comment]
原来是程序员😱

**Comment by XndroidDev** [comment]
@glhfgg1024 
感谢反馈, 1.2.0以前的版本由于证书变更会无法搜索到IP

**Comment by glhfgg1024** [comment]
@XndroidDev 谢谢回复！

**Comment by AnyWAT** [comment]
回复事小，OK（？）事大

**Comment by SeaHOH** [comment]
你慌啥，这又不是设置问题，还需要编译测试。

**Comment by XndroidDev** [comment]
@SeaHOH 
新版XX-Net(3.12.10)中, GET http://127.0.0.1:8085/module/gae_proxy/control/status 时
返回的`is_idle`一直都为0, 导致Xndroid中无法判断到底是无法连接还是空闲.

**Comment by XndroidDev** [comment]
@glhfgg1024  
请下载测试 https://raw.githubusercontent.com/XndroidDev/Xndroid-update/master/update/app-debug.apk

**Comment by SeaHOH** [comment]
`is_idle` 的判断是二十分钟无新请求，是不是有点长？
其实即使缩短我也觉得不好判断，我的做法是发送 DNS 请求，但是不适用于前置代理。

**Comment by XndroidDev** [comment]
启动XX-Net后连接池数量均为0, 此时idle应置为1, 但get到的是0, 20分钟可以改短一点.

**Comment by SeaHOH** [comment]
以前就是这样的，你如果想用连接池来判断也可以啊，无视`is_idle`就行，反正都不准确。

**Comment by glhfgg1024** [comment]
@XndroidDev @SeaHOH @AnyWAT 安装了您编译的文件后，现在1.2.2完全可以了。我的是android 5.0系统。非常感谢！
