### ISSUE TITLE
我将项目导入studio直接运行(没有修改任何代码 )  ： ’fqrouter意外退出‘

### ISSUE THREAD

**Issue by chenweihui1997** [XndroidDev/Xndroid#182]
### 直接下载release里的最新apk是可以在手机上正常运行的，是我项目少了什么东西，还是需要修改什么地方嘛? 

无法连接到这个地址：
net.xndroid E/xndroid_log: post fail:Failed to connect to /127.0.0.1:2515 url: http://127.0.0.1:2515/exit
java.net.ConnectException: Failed to connect to /127.0.0.1:2515
                                                              at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:143)
                                                              at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
                                                              at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
                                                              at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
                                                              at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
                                                              at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
                                                              at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
                                                              at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
                                                              at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
                                                              at net.xndroid.utils.HttpJson.post(HttpJson.java:67)
                                                              at net.xndroid.fqrouter.FqrouterManager.quit(FqrouterManager.java:346)
                                                              at net.xndroid.LaunchService.clearOldProcess(LaunchService.java:308)
                                                              at net.xndroid.LaunchService.access$300(LaunchService.java:39)
                                                              at net.xndroid.LaunchService$3.run(LaunchService.java:372)
                                                              at net.xndroid.WorkingDlg$1.run(WorkingDlg.java:23)
                                                              at java.lang.Thread.run(Thread.java:784)      

net.xndroid E/xndroid_log: FatalError: fqrouter意外退出
net.xndroid E/xndroid_log: ShErr> tar: fqrouter/log: No such file or directory
                                                          tar: error exit delayed from previous errors      

@XndroidDev 
[xndroid-logs.tar.gz](https://github.com/XndroidDev/Xndroid/files/2468304/xndroid-logs.tar.gz)

![screenshot_20181011-173354](https://user-images.githubusercontent.com/18424462/46795237-3e51ff00-cd7c-11e8-8b48-18d863d9092f.jpg)

**Comment by XndroidDev** [comment]
unix环境下执行./fqrouter_prebulid.sh压缩fqrouter. 或直接解压最新版apk获取内置fqrouter,xxnet, 复制到raw文件夹，详情见readme

**Comment by chenweihui1997** [comment]
这两个文件都有，fqrouter我是解压的，xxnet项目下载下来里面就有的

**Comment by chenweihui1997** [comment]
@XndroidDev 
![1539352582 1](https://user-images.githubusercontent.com/18424462/46873684-c5c96c00-ce69-11e8-9341-b84d83ceec0b.jpg)
