### ISSUE TITLE
致命错误

### ISSUE THREAD

**Issue by JMagenif** [XndroidDev/Xndroid#53]
[xndroid-logs.tar.gz](https://github.com/XndroidDev/Xndroid/files/1676737/xndroid-logs.tar.gz)
xxnet意外退出  可否麻烦看一下是什么问题额

**Comment by JMagenif** [comment]
手机是4.12版本的

**Comment by shanzigang** [comment]
我在小米盒子上面运行，xx-net同样无法启动。版本是4.2.2，是不是不支持低版本的andriod?

**Comment by XndroidDev** [comment]
@JMagenif 
```
Traceback (most recent call last):
  File "/data/data/net.xndroid/files/xndroid_files/xxnet/android_start.py", line 10, in <module>
    import OpenSSL.SSL as SSL
  File "/data/data/net.xndroid/files/xndroid_files/python/bin/../lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/data/data/net.xndroid/files/xndroid_files/python/bin/../lib/python2.7/site-packages/OpenSSL/rand.py", line 11, in <module>
    from OpenSSL._util import (
  File "/data/data/net.xndroid/files/xndroid_files/python/bin/../lib/python2.7/site-packages/OpenSSL/_util.py", line 3, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/data/data/net.xndroid/files/xndroid_files/python/bin/../lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 14, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: Cannot load library: reloc_library[1306]: 14058 cannot locate 'getline'...
```
看来还得交叉编译
http://joaoventura.net/blog/2014/python-android-5/

**Comment by XndroidDev** [comment]
@JMagenif  你试试旧版本能否正常运行

**Comment by XndroidDev** [comment]
@yutianzeabc 先试试旧版本能否正常使用

**Comment by yutianzeabc** [comment]
@XndroidDev 
V1.1.7 XX-NET意外退出
[xndroid-logs-1.1.6.tar.gz](https://github.com/XndroidDev/Xndroid/files/1844491/xndroid-logs-1.1.6.tar.gz)
V1.1.6 XX-NET意外退出
[xndroid-logs-1.1.7.tar.gz](https://github.com/XndroidDev/Xndroid/files/1844492/xndroid-logs-1.1.7.tar.gz)

**Comment by XndroidDev** [comment]
这个得花点时间

**Comment by AnyWAT** [comment]
安卓4.2.2联想手机：Root VPN运行异常，
安卓4.4.2小米手机：Root运行正常，VPN未试。
后者为前者提供代理服务正常

**Comment by XndroidDev** [comment]
@AnyWAT  可能是pie支持或库依赖问题, 导致native程序无法运行

**Comment by AnyWAT** [comment]
3.8.5及以前版本与3.8.6及以后版本，证书文件发生了变化，退回3.8.5及以前不是一个好主意🤣
建议使用3.10.4，想IP延迟小并稳定，修改 data/data/net.xndroid/files/xndroid_files/xxnet/data/gae_proxy/manual.ini
[google_ip]
max_good_ip_num = 1000 （程序默认6000太大，不好😜）
IP延时大、或转换XX-Net版本及网络卡顿，增大扫描线程（貌似保存不了）、关闭“自动调整扫描线程”（能否保存？）手动检查IP。。。

**Comment by stonyz** [comment]
同样的问题， android4.1.2. 中兴N988
