### ISSUE TITLE
XX-NET意外退出

### ISSUE THREAD

**Issue by yutianzeabc** [XndroidDev/Xndroid#80]
三星GT-S7568 安卓4.0.4 Xndroid最新稳定版 Root模式 XX-NET无响应/XX-NET意外退出
好像VPN模式也一样
[xndroid-logs.tar.gz](https://github.com/XndroidDev/Xndroid/files/1829900/xndroid-logs.tar.gz)

**Comment by XndroidDev** [comment]
4.0.4似乎有点老，没有测试过

**Comment by yutianzeabc** [comment]
@XndroidDev 所以是不兼容的缘故吗

**Comment by XndroidDev** [comment]
Traceback (most recent call last):
  File "/data/data/net.xndroid/files/xndroid_files/xxnet/android_start.py", line 10, in <module>
    import OpenSSL.SSL as SSL
  File "/data/data/net.xndroid/files/xndroid_files/python/bin/../lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/data/data/net.xndroid/files/xndroid_files/python/bin/../lib/python2.7/site-packages/OpenSSL/rand.py", line 12, in <module>
    from OpenSSL._util import (
  File "/data/data/net.xndroid/files/xndroid_files/python/bin/../lib/python2.7/site-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/data/data/net.xndroid/files/xndroid_files/python/bin/../lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 14, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: Cannot load library: reloc_library[1286]:  3708 cannot locate 'getline'...

**Comment by XndroidDev** [comment]
转到 https://github.com/XndroidDev/Xndroid/issues/53 讨论
